### ISSUE TITLE
Create an AJAX call to a/the Google Maps API

### ISSUE THREAD

**Issue by ghost** [JulieMathews/WeAreNorth#14]
**DESCRIPTION:**
One of the project requirements is to issue a request to the Google Maps API via an AJAX call.

**TASK:**
Please create use jQuery to perform this request. Please be sure to create functionality for when the promise is fulfilled, and a contingency of when the promise is not fulfilled.

The inputs from the AJAX request should be:

- Origin location
- Destination location
- Method of transportation (e.g., bus, car, etc.)
- Desired arrival time

Please work with Ben to ensure that there is error messaging, or text, that occurs if the API does not return with a response.

**ACCEPTANCE CRITERIA:**
A request can be made via a .js file to the Google Maps API and if the API resolves, then a data point is returned. If the API does not resolve, then the page has elegant handling to instruct the user of how to proceed.

- [ ]  If the API request resolves, then data is returned.
- [ ]  If the API request does not resolve, then error messaging is shown to the application user that indicates to try again at a later time.
- [ ]  Ben is informed of how to reference this AJAX call for when the button on Layout 2 is clicked.
