### ISSUE TITLE
Create a 'mindful' function that takes a user input for location and outputs a predicted base departure time

### ISSUE THREAD

**Issue by TammyLeeSeattle** [JulieMathews/WeAreNorth#17]
**DESCRIPTION:**
On the front-end, in Layout 2, we want a user to be able to provide a 'starting' (read: origin) location, a destination location, and a desired arrival time.

Based on their destination location and desired arrival time, we want to be able to provide the user with a "base" predicted time that they must depart, if no other factors were involved.

The difficulty is that the front-end needs to enforce user inputs based on what the Google API requires as inputs. For example, does the API require a city name? State? Zip code? What happens if the user inserts a city that the API does not recognize? For example, what happens if the user inputs "Ballard, WA", which is not a "real city"?

In Ben's [Item](https://github.com/JulieMathews/WeAreNorth/issues/16), we ideally should enforce on the front-end, the right format that the API wants.

Please work with Ben to ensure that regardless of what the user enters, one of the below experiences is possible:

- An origin location, a destination location, and desired arrival time is entered such that a predicted departure time is provided.
- If any of the user input criteria -- origin, destination or arrival time -- are not valid, then the front-end has a way to guide the user about how to input values correctly.

**TASK:**
Please ensure create a function that engages with the Google API such that:

- There are code comments that show what the required input formats are.
- There are code comments that show what the output formats are.
- Takes the user input of a location as a parameter of the function then outputs a forecast.
  - If the user inputs an invalid location, then the front-end should show something that indicates to the user of why their location was invalid.

**ACCEPTANCE CRITERIA:**
As a user, if I input "Bellingham, WA" as my origin, and "Seattle, WA" as my destination, and "Sunday, 2/3/19 at 9 am" as my desired arrival time, then I get a predicted departure time. If I input a fake city, such as "Seeeeattle, WA", then I see something on the front-end that shows me how I can fix my input.

- [ ] There are code comments that show what the required input formats are.
- [ ] There are code comments that show what the output formats are.
- [ ] Takes the user input of a location as a parameter of the function then outputs a forecast.
  - [ ] If the user inputs an invalid location, then the front-end should show something that indicates to the user of why their location was invalid.
