### ISSUE TITLE
Create an "ID" layout guide for the rest of the team

### ISSUE THREAD

**Issue by ghost** [JulieMathews/WeAreNorth#5]
**BACKGROUND**

The Layouts Requirement outlines the format of the three layouts. 

**TASK:**

Please create a basic image (in an image program) that defines the rough layout of the three interfaces. In each image, please denote that IDs that the backend team will need to reference within the layouts.

**ACCEPTANCE CRITERIA:**
- [ ] An image for Layout 1 is hosted that is accessible by the rest of the team.
- [ ] An image for Layout 2 is hosted that is accessible by the rest of the team.
- [ ] An image for Layout 3 is hosted that is accessible by the rest of the team.
- [ ] Each hosted image has the names of each ID.
- [ ] Sonja, Julie and Tammy are notified of the place of these images.
